server:
  port: 8080
spring:
  application:
    name: my-workflow-app
  datasource:
    url: jdbc:mysql://103.149.170.20:3306/db_A46764
    username: A46764
    password: A46764@thanglong
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
camunda.bpm:
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
  database:
    schema-update: true
  admin-user:
    id: admin
    password: "123456"
    first-name: Admin
    last-name: User
    email: admin@example.com
  generic-properties:
    enforce-history-time-to-live: false

#zeebe:
#  client:
#    cloud:
#      cluster-id: "de660ef3-fc2a-4780-9d43-d21394ee649c"
#      client-id: "So_Fzb4DBuyeBDyN~BXdHxg242YtYevB"
#      client-secret: "y3KxYPmcpnU2eVnO.XPXxP9JpqR-cFFHPddQbxRpAAdoAO6OjC4EZhfbkgf7h3Tm"
#      region: "sin-1"